[versions]
agp = "8.5.1"
junit-jupiter = "5.10.3"
mockito = "5.12.0"
ftcrobot = "9.0.1"
roadrunner = "0.5.5"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref ="junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref ="junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
ftcrobotcore = { module = "org.firstinspires.ftc:RobotCore", version.ref = "ftcrobot" }
roadrunner = { module = "com.acmerobotics.roadrunner:core", version.ref = "roadrunner" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }

