plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish'
}

group = 'team.techtigers.ftc'
version = '2.0.0-rc10'

android {
    namespace 'team.techtigers.core'
    compileSdk 30

    defaultConfig {
        minSdk 24
        targetSdk 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencies {
    testImplementation libs.junit.jupiter
    testImplementation libs.junit.jupiter.params
    testImplementation libs.mockito.core
    implementation libs.ftcrobotcore
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

afterEvaluate {
    publishing {
        publications {
            create("release", MavenPublication) {
                from components.release

                groupId = project.group
                artifactId = 'ftc-core'
                version = project.version

                pom {
                    name = 'Tech Tigers FTC Core Library'
                    description = 'A library which contains multiple resources for FTC teams,' +
                            ' including drivers for LED displays,  route planners, and other' +
                            'useful utilities.'
                    url = 'http://www.techtigers.team'
                    licenses {
                        license {
                            name = 'The MIT License'
                            url = 'https://opensource.org/license/mit'
                        }
                    }
                    developers {
                        developer {
                            id = 'techtigers'
                            name = 'Tech Tigers'
                            email = 'techtigers33958@gmail.com'
                        }
                    }
                    scm {
                        connection = 'scm:git:git://github.com:techtigers-ftc/ftc-core.git'
                        developerConnection = 'scm:git:https://github.com:techtigers-ftc/ftc-core.git'
                        url = 'https://github.com/techtigers-ftc/ftc-core'
                    }
                }
            }
        }
    }
}